### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by maxmanusv1** [mizutama1233/Discord-Token-Generator#1]
It returns following error on  `https://discord.com/api/v10/auth/register` endpoint.
{'captcha_key': ['invalid-response'], 'captcha_sitekey': '4c672d35-0701-42b2-88c3-78380b0db560', 'captcha_service': 'hcaptcha'}

**Comment by mizutama1233** [comment]
Are you setting the email in main.py? It's commented out by default.

**Comment by maxmanusv1** [comment]
yeah, i am generating emails, username and password with my own code. Also i implemented capsolver&capmonster services and tried both services to solve Hcaptcha. should i use nocaptchaai service? will it fix the problem?

**Comment by mizutama1233** [comment]
I have only tried the NocaptchaAi service. If you are using a different service, I wouldn't know, and this issue may not be related to this project

**Comment by maxmanusv1** [comment]
I though something is wrong with headers and payload but it seems good too. I will try other services.
